### ISSUE TITLE
No styling needed?

### ISSUE THREAD

**Issue by lydell** [jystic/elm-font-awesome#11]
https://ellie-app.com/5zpcKw7N6a1/0

The readme says:

> Every Font Awesome icons automatically inherits CSS size and colors from their parents.

Looking at the source, I can see how `currentColor` is used, but nothing about size.

https://github.com/jystic/elm-font-awesome/blob/3c61d50f57809e8bf7b443f892b12e494eaadf30/src/FontAwesome/Internal.elm#L9-L17

Compare to the CSS FontAwesome uses:

https://github.com/FortAwesome/Font-Awesome/blob/28d2f62b6cc14e782ef5f04e567397f2af804fc5/svg-with-js/css/fa-svg-with-js.css#L8-L13

Here’s what the above Ellie looks like:

![screenshot from 2018-05-03 11-34-20](https://user-images.githubusercontent.com/2142817/39569611-03076848-4ec6-11e8-886f-822c4fc49a5f.png)

I ended up wrapping the icons in a span with this CSS:

```css
.faTMP svg {
  display: inline-block;
  height: 1em;
  overflow: visible;
  font-size: inherit;
  vertical-align: -0.125em;
}
```

Am I missing something?
